---
- name: A simple file playbook
  hosts: planetexpress
  gather_facts: yes
  connection: ansible.builtin.ssh

  tasks:
   - name: make a directory
     ansible.builtin.file:
       path: ~/output/
       state: directory

         #   - name: use shell module with wildcarding
         #     ansible.builtin.shell: echo $HOME >> ~/output/path.txt
         #
         #
   - name: use copy to avoid using a shell command
     ansible.builtin.copy:
       content: "{{ ansible_env.HOME }}"           # this retrieves env info from gathered facts ("left side" of the shell command)
       dest: ~/output/path.txt                     # ("right side" of the shell command)
       force: yes 
