- name: My Arista Playbook
  hosts: switches
  gather_facts: false

  vars_files:
    - ~/switch.creds

  tasks:
  - name: configure the login banner
    eos_banner:
      banner: login
      text: |
         __________________
         This is a switch 
         ------------------
            \   ^__^
             \  (oo)\_______
                (__)\       )\/\
                   ||----w |
                   ||     ||
      state: "{{ herethere }}"

