---
- name: Using a complex vars file
  hosts: localhost
  gather_facts: False

  vars_files:
    - ~/mycode/vars/titanvars.yml

  tasks:
  - name: debug with_dict
    ansible.builtin.debug:
      var: "{{ item }}"
    loop: "{{ prefix_list }}"  # this will FAIL because prefixlist is a dictionary

